language: julia
julia:
  - release
  # - nightly
script:
  - julia -e 'Pkg.clone(pwd())'
  - julia -e "Pkg.build(\"Converters\")"
  - julia --check-bounds=yes --code-coverage -e "Pkg.test(\"Converters\", coverage = true)"
after_success:
  - julia -e 'cd(Pkg.dir("Converters")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
