language: julia
julia:
  - release
  # - nightly
script:
  - pwd
  - julia -e 'Pkg.clone(pwd())'
  - julia -e "Pkg.build(\"Biryani\")"
  - julia --check-bounds=yes --code-coverage -e "Pkg.test(\"Biryani\", coverage = true)"
after_success:
  - julia -e 'cd(Pkg.dir("Biryani")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
